# Generated by Django 5.1.5 on 2026-08-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When this agent was last given a ticket. The rotation tiebreak in tickets.services.ticket_service.pick_next_agent orders on it, so two agents at equal load alternate instead of the lower id always winning.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Round-robin assignment skips unavailable agents.'),
        ),
    ]
