# Generated by Django 5.1.5 on 2026-09-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('ticket_assigned', 'Ticket assigned'), ('ticket_escalated', 'Ticket escalated'), ('ticket_sla_breached', 'SLA breached')], db_index=True, max_length=32),
        ),
    ]
