import { Toaster as SonnerToaster, toast } from "sonner";

/**
 * Toasts, via **sonner** — one library, chosen here so stories 07–09 do not
 * introduce a second.
 *
 * Why sonner over shadcn's own toast primitive: shadcn's is generated by the
 * CLI (Node 20, this project is on Node 18) and its Radix `Toast` provider is
 * the one piece of that set with known friction under React 19's stricter
 * effect ordering. sonner is a single self-contained component, direction-aware
 * from the document's `dir`, and needs no provider tree.
 *
 * Usage: `import { toast } from "@/components/ui/toast"` then
 * `toast.success(t("kitchen.toastMessage"))`. **Translate at the call site** —
 * a toast helper that takes keys hides the interpolation the caller needs.
 */

export function Toaster() {
  return (
    <SonnerToaster
      position="bottom-center"
      toastOptions={{ className: "font-sans text-[13px]" }}
    />
  );
}

export { toast };
