import type {
  CustomerDetail,
  Me,
  Sla,
  TicketDetail,
  TicketListRow,
  TicketMessage,
} from "@/api/types";

/** Shared fixtures, shaped exactly like the serializers they stand in for. */

export const okSla = (over: Partial<Sla> = {}): Sla => ({
  state: "ok",
  seconds_remaining: 3600,
  target_minutes: 120,
  policy_name: "Standard-Normal",
  ...over,
});

export const me = (over: Partial<Me> = {}): Me => ({
  id: 3,
  username: "agent@demo",
  email: "agent@demo.local",
  full_name: "Yousef Al-Qahtani",
  role: "agent",
  department: "technical",
  branch: "riyadh",
  tier: 2,
  language: "en",
  is_available: true,
  ...over,
});

export const listRow = (over: Partial<TicketListRow> = {}): TicketListRow => ({
  id: 1,
  number: "TK-0001",
  subject: "SMS notifications arriving hours late",
  priority: "high",
  status: "open",
  channel: "sms",
  customer_name: "Khalid Omari",
  assignee_name: "Yousef Al-Qahtani",
  category_name: "Technical",
  created_at: "2026-08-26T09:00:00Z",
  sla_resolution_due_at: "2026-08-28T09:00:00Z",
  is_breached: false,
  resolution_sla: okSla(),
  ...over,
});

export const detail = (over: Partial<TicketDetail> = {}): TicketDetail => ({
  id: 1,
  number: "TK-0001",
  subject: "SMS notifications arriving hours late",
  description: "Dispatch alerts are reaching our crews hours late.",
  customer: 10,
  customer_name: "Khalid Omari",
  customer_company: "Omari Contracting",
  customer_tier: "enterprise",
  contact: null,
  contact_name: "",
  category: null,
  tags: [],
  priority: "high",
  status: "new",
  channel: "sms",
  assignee: null,
  created_by: null,
  department: "technical",
  branch: "riyadh",
  assignment_reason: "auto-assigned by rule R-12",
  escalation_level: 0,
  escalated_at: null,
  first_response_at: null,
  resolved_at: null,
  closed_at: null,
  sla_policy: 1,
  sla_policy_name: "Standard-Normal",
  sla_response_due_at: "2026-08-28T09:00:00Z",
  sla_resolution_due_at: "2026-08-29T09:00:00Z",
  sla_response_breached: false,
  sla_resolution_breached: false,
  ai_summary: "",
  ai_suggested_category: null,
  watcher_count: 2,
  csat_score: null,
  is_breached: false,
  response_sla: okSla(),
  resolution_sla: okSla(),
  // A `new` ticket, per ticket_service.ALLOWED_TRANSITIONS.
  allowed_transitions: ["escalated", "open"],
  created_at: "2026-08-26T09:00:00Z",
  updated_at: "2026-08-26T09:00:00Z",
  ...over,
});

export const message = (over: Partial<TicketMessage> = {}): TicketMessage => ({
  id: 1,
  ticket: 1,
  author: 10,
  author_name: "Khalid Omari",
  author_role: "customer",
  body: "Dispatch alerts are reaching our crews hours late.",
  is_internal: false,
  channel: "sms",
  created_at: "2026-08-26T09:05:00Z",
  ...over,
});

export const customer = (over: Partial<CustomerDetail> = {}): CustomerDetail => ({
  id: 10,
  name: "Khalid Omari",
  company: "Omari Contracting",
  email: "k.omari@omaricon.sa",
  phone: "+966 56 118 3305",
  whatsapp: "+966 56 118 3305",
  tier: "enterprise",
  branch: 1,
  branch_name: "Riyadh",
  preferred_language: "en",
  contacts: [],
  open_ticket_count: 4,
  total_ticket_count: 9,
  created_by: null,
  created_at: "2026-01-01T00:00:00Z",
  updated_at: "2026-01-01T00:00:00Z",
  ...over,
});
